controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

ackermann_steering_controller:
  ros__parameters:
    wheelbase: 0.25
    front_wheel_track: 0.22
    rear_wheel_track: 0.22
    front_wheels_radius: 0.05
    rear_wheels_radius: 0.05
    
    front_wheels_names:
      - front_left_steering_joint
      - front_right_steering_joint
    
    rear_wheels_names:
      - rear_left_wheel_joint
      - rear_right_wheel_joint
      
    open_loop: false
    publish_rate: 50.0
    velocity_rolling_window_size: 10
    
    # 确保cmd_vel话题可用
    use_stamped_vel: false
    
    # 启用里程计发布
    enable_odom_tf: true
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    odom_only_twist: false
    publish_odom: true
    publish_transformed_twist: true
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]