<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="simple_bot">

    <!-- Included URDF/XACRO Files -->
    <xacro:include filename="$(find simple_robot)/urdf/robot.gazebo.xacro" />

    <xacro:property name="chassis_length" value="0.4"/>
    <xacro:property name="chassis_width" value="0.2"/>
    <xacro:property name="chassis_height" value="0.1"/>
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_width" value="0.04"/>
    <xacro:property name="wheelbase" value="0.25"/>
    <xacro:property name="track" value="0.22"/>

    <link name="base_link">
    </link>

    <link name="chassis_link">
        <visual>
            <origin xyz="0 0 0.1"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="blue">
                <color rgba="0.2 0.2 1.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0.1"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0.1" rpy="0 0 0"/>
            <mass value="5"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
        </inertial>
    </link>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="0 0 0"/>
    </joint>

    <!-- Rear Wheels (Driving) -->
    <xacro:macro name="rear_wheel" params="prefix y_offset">
        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="1.5707 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="black">
                    <color rgba="0.3 0.3 0.3 1.0"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="1.5707 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.5"/>
                <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
            </inertial>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <origin xyz="${-wheelbase/2} ${y_offset} 0" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>

    <xacro:rear_wheel prefix="rear_left" y_offset="${track/2}"/>
    <xacro:rear_wheel prefix="rear_right" y_offset="${-track/2}"/>

    <!-- Front Wheels (Steering) -->
    <xacro:macro name="front_wheel" params="prefix y_offset">
        <link name="${prefix}_steering_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.02 0.02 0.02"/>
                </geometry>
                <material name="red">
                    <color rgba="1.0 0.0 0.0 1.0"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.02 0.02 0.02"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.1"/>
                <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
            </inertial>
        </link>

        <joint name="${prefix}_steering_joint" type="revolute">
            <parent link="base_link"/>
            <child link="${prefix}_steering_link"/>
            <origin xyz="${wheelbase/2} ${y_offset} 0" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
            <limit lower="-0.6" upper="0.6" effort="10" velocity="1.0"/>
        </joint>

        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="1.5707 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="black">
                    <color rgba="0.3 0.3 0.3 1.0"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="1.5707 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.5"/>
                <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
            </inertial>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="${prefix}_steering_link"/>
            <child link="${prefix}_wheel_link"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>

    <xacro:front_wheel prefix="front_left" y_offset="${track/2}"/>
    <xacro:front_wheel prefix="front_right" y_offset="${-track/2}"/>

    <!-- Gazebo wheel friction properties -->
    <gazebo reference="rear_left_wheel_link">
        <mu1>0.8</mu1>
        <mu2>0.8</mu2>
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="rear_right_wheel_link">
        <mu1>0.8</mu1>
        <mu2>0.8</mu2>
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="front_left_wheel_link">
        <mu1>0.8</mu1>
        <mu2>0.8</mu2>
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="front_right_wheel_link">
        <mu1>0.8</mu1>
        <mu2>0.8</mu2>
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- ros2_control hardware interface -->
    <ros2_control name="GazeboSystem" type="system">
        <hardware>
            <plugin>gazebo_ros2_control/GazeboSystem</plugin>
        </hardware>

        <!-- Steering Joints -->
        <joint name="front_left_steering_joint">
            <command_interface name="position"/>
            <state_interface name="position"/>
            <state_interface name="velocity"/>
        </joint>
        <joint name="front_right_steering_joint">
            <command_interface name="position"/>
            <state_interface name="position"/>
            <state_interface name="velocity"/>
        </joint>

        <!-- Driving Joints -->
        <joint name="rear_left_wheel_joint">
            <command_interface name="velocity"/>
            <state_interface name="position"/>
            <state_interface name="velocity"/>
        </joint>
        <joint name="rear_right_wheel_joint">
            <command_interface name="velocity"/>
            <state_interface name="position"/>
            <state_interface name="velocity"/>
        </joint>
    </ros2_control>

</robot>
